### ISSUE TITLE
Results are not valid dns resolvers

### ISSUE THREAD

**Issue by bugbaba** [BBerastegui/fresh-dns-servers#1]
Hey Borja,

The projects looks promising, But I guess the [dnsvalidator](https://github.com/vortexau/dnsvalidator) you are relying on is not efficient in its job, or may be these don't stay valid even for single day.

I tried validating couple of them and all of them failed.

![image](https://user-images.githubusercontent.com/29960776/68659170-c8126400-055c-11ea-96e9-a7beddd85407.png)

https://github.com/BBerastegui/fresh-dns-servers/blob/30303374e8b1e30d5c67816a81eb82441abf7663/resolvers.txt#L385

https://github.com/BBerastegui/fresh-dns-servers/blob/30303374e8b1e30d5c67816a81eb82441abf7663/resolvers.txt#L396

may be you can try the old school way using bash and then benchmark the results.
``` bash
#!/bin/bash
validip=$(dig @1.1.1.1 +short example.com)
while read -r ip; do
    dig @"$ip" +short example.com
done < resolvers.txt


```

**Comment by BBerastegui** [comment]
Do you know if Cloudflare dns's (1.1.1.1) do throttling or blacklisting? Because if so, i would prefer not to automate such check :D

**Comment by bugbaba** [comment]
hey @BBerastegui,
In this bash script case we are using 1.1.1.1 or any known valid resolver to get the valid result once only, after that we are making the dns queries via the potential valid revolvers and then comparing the results with the results we got from the valid resolver.

So I don't think cloudflare throttling will come into this case. Correct me if I am wrong or failed to get what you were trying to say :)

**Comment by BBerastegui** [comment]
Oh yeah, you are totally right. Sorry I went through your comment too fast XD

I'll try to do that!

**Comment by BBerastegui** [comment]
I just saw that dnsvalidator itself provides a flag for this to be done automatically (using a baseline DNS to check the validity of the rest of resolvers) so I've enabled it :D

Let's see how this changes, thanks!
