### ISSUE TITLE
DNS Servers missing

### ISSUE THREAD

**Issue by phenix-sec** [BBerastegui/fresh-dns-servers#3]
Hi,

Just wanted to let you know that i've just tested with dnsvalidator the 2 lists and i've got over 2000 valid dns servers, whereas your current list has over 300. There are also some well known servers that are missing from your list like 1.0.0.1.
just trying to help out.

**Comment by BBerastegui** [comment]
I'll take a look at it. Thanks!

**Comment by BBerastegui** [comment]
I've migrated to a Github action that runs 24h periodically. Lets see what we get from that ;)
