### ISSUE TITLE
Update README to explain the origin of most of the IP addresses

### ISSUE THREAD

**Issue by covuworie** [BBerastegui/fresh-dns-servers#6]
Hi, thanks very much for providing this large list of public dns servers that are frequently checked - it's a great resource!

I have a question / update suggestion for the README which I see was last updated 3 years ago. The [resolvers.csv](https://github.com/BBerastegui/fresh-dns-servers/blob/master/resolvers.csv) contains over 84K IP addresses. Yet in the README you reference two origin txt lists which contain only 5769 and 993 IP addresses. So where do the remaining approximate 78K IP addresses come from?

I think it would be great if you could update the README to provide this information.

Thank you.

**Comment by covuworie** [comment]
Hi, okay I see this is not valid anymore since most of the 84K+ are duplicate values. At present there are 1996 unique values. I presume all of these values come from the two lists in the README? If so, then my new suggestion is to remove the duplicate values from the csv file instead.

**Comment by BBerastegui** [comment]
Heyo @covuworie !

I had this a little bit abandoned, let me get some time and take a look on how can I get it to work "by itself" again :D

**Comment by covuworie** [comment]
Thanks for taking a look at this @BBerastegui.

**Comment by BBerastegui** [comment]
Hey @covuworie , I setup a Github action that will run periodically every 24h updating the list of resolvers. Lets see if we get something a bit more solid now ;)

**Comment by covuworie** [comment]
Thanks very much @BBerastegui!
