### ISSUE TITLE
Only 6 DNS servers in the resolvers list

### ISSUE THREAD

**Issue by covuworie** [BBerastegui/fresh-dns-servers#8]
Hi @BBerastegui,

Hope you are doing well! 

Just noticed there are only 6 DNS servers in the [resolvers.txt](https://github.com/BBerastegui/fresh-dns-servers/blob/master/resolvers.txt) list. Before the number was approaching 1000. Not sure when this difference happened. Any idea why less servers are passing your checks now?

Cheers!

**Comment by BBerastegui** [comment]
Yup, I think it's because we are hammering too fast and too frequently. I've changed the job to run every 48h and reduced the threads to from 60 to 30.

Let's see what happens in the next days!

**Comment by BBerastegui** [comment]
Looks like we are back on track @covuworie !
